//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public CAPACITACION()
        {
            this.DETALLE_CAPACITACION = new HashSet<DETALLE_CAPACITACION>();
            this.USUARIO_CAPACITACION = new HashSet<USUARIO_CAPACITACION>();
            this.TRABAJADOR = new HashSet<TRABAJADOR>();
        }
    
        public decimal ID_CAPACITACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_FIN { get; set; }
        public decimal ID_TIPOCAP { get; set; }
        public decimal ID_RELATOR { get; set; }
    
        public virtual TIPO_CAPACITACION TIPO_CAPACITACION { get; set; }
        public virtual RELATOR RELATOR { get; set; }
        public virtual ICollection<DETALLE_CAPACITACION> DETALLE_CAPACITACION { get; set; }
        public virtual ICollection<USUARIO_CAPACITACION> USUARIO_CAPACITACION { get; set; }
        public virtual ICollection<TRABAJADOR> TRABAJADOR { get; set; }
    }
}
