//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CAPACITACION
    {
        public decimal ID_DETALLECAP { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string FECHA_CLASE { get; set; }
        public string HORA_CLASE { get; set; }
        public string DURACION_HORAS { get; set; }
        public decimal ID_CAPACITACION { get; set; }
    
        public virtual CAPACITACION CAPACITACION { get; set; }
    }
}
