//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        public decimal ID_DIAGNOSTICO { get; set; }
        public string DESCRIPCION { get; set; }
        public string EXAMEN { get; set; }
        public Nullable<decimal> ID_FICHA { get; set; }
        public Nullable<decimal> ID_VISITA { get; set; }
    
        public virtual FICHA_MEDICA FICHA_MEDICA { get; set; }
        public virtual VISITA_MEDICA VISITA_MEDICA { get; set; }
    }
}
