//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACION
    {
        public EVALUACION()
        {
            this.USUARIO_EVALUACION = new HashSet<USUARIO_EVALUACION>();
        }
    
        public decimal ID_EVALUACION { get; set; }
        public decimal ID_TIPOEV { get; set; }
        public string NOMBRE_EV { get; set; }
        public Nullable<decimal> ID_TECNICO { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
        public string ENCARGADO_EV { get; set; }
        public string DESC_EV { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<System.DateTime> FECHA_CRECION { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPO_EVALUACION TIPO_EVALUACION { get; set; }
        public virtual ICollection<USUARIO_EVALUACION> USUARIO_EVALUACION { get; set; }
    }
}
