//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA_MEDICA
    {
        public FICHA_MEDICA()
        {
            this.DIAGNOSTICO = new HashSet<DIAGNOSTICO>();
        }
    
        public decimal ID_FICHA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
    
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
