//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.VISITA_MEDICA = new HashSet<VISITA_MEDICA>();
        }
    
        public decimal ID_MEDICO { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string EMAIL { get; set; }
        public string VALIDADO { get; set; }
    
        public virtual ICollection<VISITA_MEDICA> VISITA_MEDICA { get; set; }
    }
}
