//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafeEntities : DbContext
    {
        public SafeEntities()
            : base("name=SafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<DETALLE_CAPACITACION> DETALLE_CAPACITACION { get; set; }
        public DbSet<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<EVALUACION> EVALUACION { get; set; }
        public DbSet<FICHA_MEDICA> FICHA_MEDICA { get; set; }
        public DbSet<INSTALACION> INSTALACION { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<RELATOR> RELATOR { get; set; }
        public DbSet<TIPO_CAPACITACION> TIPO_CAPACITACION { get; set; }
        public DbSet<TIPO_EMPRESA> TIPO_EMPRESA { get; set; }
        public DbSet<TIPO_EVALUACION> TIPO_EVALUACION { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<TRABAJADOR> TRABAJADOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<USUARIO_CAPACITACION> USUARIO_CAPACITACION { get; set; }
        public DbSet<USUARIO_EVALUACION> USUARIO_EVALUACION { get; set; }
        public DbSet<USUARIO_VISITA> USUARIO_VISITA { get; set; }
        public DbSet<VISITA_MEDICA> VISITA_MEDICA { get; set; }
    }
}
