//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CAPACITACION
    {
        public TIPO_CAPACITACION()
        {
            this.CAPACITACION = new HashSet<CAPACITACION>();
        }
    
        public decimal ID_TIPOCAP { get; set; }
        public string TEMA { get; set; }
    
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
    }
}
