//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.FICHA_MEDICA = new HashSet<FICHA_MEDICA>();
            this.USUARIO_EVALUACION = new HashSet<USUARIO_EVALUACION>();
            this.USUARIO_CAPACITACION = new HashSet<USUARIO_CAPACITACION>();
            this.USUARIO_VISITA = new HashSet<USUARIO_VISITA>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public string RUT_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public decimal ID_TIPOUS { get; set; }
        public decimal ID_EMPRESA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<FICHA_MEDICA> FICHA_MEDICA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_EVALUACION> USUARIO_EVALUACION { get; set; }
        public virtual ICollection<USUARIO_CAPACITACION> USUARIO_CAPACITACION { get; set; }
        public virtual ICollection<USUARIO_VISITA> USUARIO_VISITA { get; set; }
    }
}
